### ISSUE TITLE
Can't run the server

### ISSUE THREAD

**Issue by davidrock** [StreamMachine/StreamMachine#102]
I don't know whether I am doing anything wrong, but when I try to run this line:

.\streammachine-cmd --config ./config/standalone.json

But the only thing happens is to open the notepad with the content of "streammachine-cmd" file.

Am I missing something ? The documentation is not so clear about that.

**Comment by tdzienniak** [comment]
I presume you are on Windows. On Windows you can't use cmd files from main directory, they are runnable for linux only. Try this:
```
node streammachine-cmd --config ./config/standalone.json
```

**Comment by horseyhorsey** [comment]
Worked for me on Windows, thanks.

**Comment by nakedsushi** [comment]
@davidrock thanks for confirmation. Closing this.
