### ISSUE TITLE
Analytics: ES Mapping needs to include client.ua unanalyzed

### ISSUE THREAD

**Issue by ewr** [StreamMachine/StreamMachine#30]
Currently, `client.ua` is a string, which defaults to analyzed. The analyzer doesn't do anything useful with a UA and analyzed prevents us from bucketing by full UA, etc.

**Comment by miksago** [comment]
I'm sure we've chatted about this in the past, but it seems you have two analytics problems:
1) Request based analytics (UAs, which stream, total listen time)
2) Live stats (bytes sent, number of active clients, etc)

For point two, I think you'd be better off making it dump out to a Statsd endpoint, which means for the Request based analytics, you could use a standard ELK stack with logstash tailing streammachines' request logs.

**Comment by ewr** [comment]
I actually have three:

1) Listening event: HLS segment request, part of a shoutcast request, etc.
2) Listening session: Rollup of the listening events in a session, to get total duration
3) Server stats: Bytes sent, etc, plus also stats about things like stream sources and stream source latency

1 and 2 are currently implemented via the analytics module. I would like to look at potentially decoupling it (or at least allowing you to choose from various implementations), but the rollup from 1 to 2 is something that's still going to need a component running somewhere. I've been pleased with going straight to ES, but supporting other paths always makes sense.

For 3, we're currently rolling out [Prometheus](http://prometheus.io) at SCPR, so I've been working on adding those sorts of metrics via a Prometheus metrics endpoint:

https://github.com/StreamMachine/StreamMachine/tree/PrometheusMetrics

You're definitely right, though, that a pluggable output system makes sense there too.

**Comment by miksago** [comment]
For segment requests, surely those could be in a JSON log format? And then you just have a tool that reads the log file and performs the rollups — essentially you want these stats to be outside of your application code, such that them not working doesn't cause the stream server to go down.

Those are metrics that you want after the fact.

In real-time you would more want metrics like Requests/second or Listeners/second type thing.

**Comment by ewr** [comment]
All interaction logging goes through the normal log channels, so there's already the means to write that out to JSON. Putting it straight into ES has been convenient for our production, though.

Definitely agree on not wanting an analytics issue to take down the server and on wanting to just pull that piece of the puzzle into a separate process. I don't love log writing and tailing as an import mechanism, but certainly that would work. Letting the slaves write log events into Rabbit or Redis or something like that would work as well. The current setup hasn't created any production issues (if our ES connection fails we just lose writes) and therefore hasn't been a big priority, but it isn't ideal.

The stat that we typically want for charting is Average Listeners over a given time period (a minute, 10 minutes, etc). We'll then query that out by certain clients, streams, etc.

**Comment by miksago** [comment]
For Average Listeners, I'd definitely be using the Gauge metric type from prometheus for that. I'm fairly certain you can do that in real-time and bucket by windowing functions, e.g., using [`avg_over_time`](http://prometheus.io/docs/querying/functions/#<aggregation>_over_time():-aggregating-values-over-time:)

As for other data, I'd be doing that at the log level, perhaps having a log sink for it that can write out to something other that standard out, e.g., rabbitmq, or kafka

**Comment by miksago** [comment]
See also what [12 Factor Apps](http://12factor.net/logs) has to say about logs.

**Comment by ewr** [comment]
It says they should all be written to stdout... I'm not really a 12-factor guy (I like config files, just ones that get injected via a deploy system). 

Using something like a Prometheus gauge for a top-line listener number is fine, and is something I intend to add, but that's a supplement to what we pull out of ES, not a replacement for it. We're able to do some pretty cool things on the live data with ES aggregations.

One note on listener count: With HLS, there is no concept of connected listeners like there is for Shoutcast. There are active sessions, but a listener is only connected and downloading data maybe 2-3 secs every 20 seconds. That's why we pull it out of the delivered durations.

**Comment by miksago** [comment]
hmm, okay; I've been drifting more and more towards 12 factor, just as I've started to see some pretty awful stuff in modern apps where they deviate from it. i.e., logging taking down the server or stats interfering with operations

**Comment by ewr** [comment]
I guess I had been holding off on closing this until I deployed the change, but we've been running it in testing for a while now.
