### ISSUE TITLE
Config options for ProxyRoom

### ISSUE THREAD

**Issue by scrudge** [StreamMachine/StreamMachine#40]
I can't find an example config to proxy an existing icecast stream.

Thanks

**Comment by ewr** [comment]
What? Our sparse documentation doesn't answer all your questions? :)

Basically a proxy source is created via specifying an `http://` fallback URL in the stream config. Here's the code that loads it up:

https://github.com/StreamMachine/StreamMachine/blob/cc7c69b174469e9e42e3d76ce3290a0651e8e434/src/streammachine/master/stream.coffee#L108-L127

So in your stream config it would just be something like:

```json
{
  "key":"mystream",
  "format": "mp3",
  "fallback": "http://my-stream-path/path"
}
```

It's expecting MP3 or AAC, broadcast from something Icecast-looking.

**Comment by scrudge** [comment]
Thanks, that seems to have worked.  But I still can't connect to the stream with vlc.  Do I need to specify an output in the config.  here's what I'm using:

{
        "port":                     8000,
        "source_port":  8001,
        "log": {
                "stdout":     true
        },
        "streams": {
                "test": {
                        "key":              "test",
                        "root_route":       true,
                        "format": "mp3",
                        "fallback": "http://audio.wbhm.org:8000/live.mp3"
                }
        }
}

The API is showing the stream:

http://home.larryowen.net:8000/api/streams

**Comment by ewr** [comment]
Your config is good, but there's something in the incoming mp3 stream that our mp3 parser doesn't like... Let me see if I can figure out what.

**Comment by scrudge** [comment]
Thanks, I have access to the incoming icecast server, if you need any config info.

**Comment by ewr** [comment]
Give master a shot. I was incorrectly calculating mp3 frame size, but apparently we had never run across it in the frequency / bit-rate combos we use.

**Comment by scrudge** [comment]
It works. Thanks for the quick fix. You can hear the result at http://home.larryowen.net:8000/test.mp3

One more question, what's the url to access HLS?

**Comment by ewr** [comment]
:+1: 

For single-variant HLS, it's just `stream.m3u8`, so in your case `http://home.larryowen.net:8000/test.mp3.m3u8`

For multi-variant HLS, you create multiple streams and give them the same `group` param to turn them into a stream group. You then have a master playlist at `/sg/group.m3u8` that lists the variant playlists.

The logic around streams -> stream groups is one of the next things I want to clean up. It was definitely a "How little can I change to get this working?" implementation, rather than a well-architected one.

**Comment by scrudge** [comment]
Awesome.  I'm going to tinker with that.  This is exactly what I I needed.  I appreciate the work.

**Comment by ewr** [comment]
Feel free to drop me an email at e@ewr.is to chat more about what you want it to do. StreamMachine is very much a work in progress, even though we've had it in production for four years now.
