### ISSUE TITLE
Invalid source crashes SourceIn instead of being rejected

### ISSUE THREAD

**Issue by pedropapa** [StreamMachine/StreamMachine#42]
Hello,
Right after I install StreamMachine, I just put the server on and attempted to connect to it and stream musics.

I got the following error:

```
root@brazucas:/home/brazucas/StreamMachine# node index.js
adding Console transport
20171 -- debug: StreamMachine standalone initialized.
20171 -- debug: Attaching listener for SIGUSR2 restarts.
20171 -- info: Attaching listeners.
20171 -- debug: Standalone is listening on port 8000
20171/master -- debug: In configure with 
20171/slave -- debug: In slave configureStreams with  
20171/sourcein -- debug: Incoming source attempt.

/home/brazucas/StreamMachine/src/streammachine/master/source_in.coffee:216
        _ref = match.slice(1, 6), this.info.method = _ref[0], this.info.url = 
                     ^
TypeError: Cannot call method 'slice' of null
  at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.REQUEST_LINE (/home/brazucas/StreamMachine/src/streammachine/master/source_in.coffee:189:99)
  at IcyParser.module.exports.SourceIn.IcyParser.IcyParser.execute (/home/brazucas/StreamMachine/src/streammachine/master/source_in.coffee:150:17)
  at Socket.<anonymous> (/home/brazucas/StreamMachine/src/streammachine/master/source_in.coffee:47:20)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:407:10)
  at emitReadable (_stream_readable.js:403:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

this happens everytime I attempt to connect to the source stream, I'm using SAM Broadcaster program to connect.

**Comment by ewr** [comment]
In SAMcast, what server type are you using?

**Comment by pedropapa** [comment]
https://www.dropbox.com/s/hyc5orimb2po0ce/b92abc09a8a9cab4088a85f213027e2f.jpg?dl=0

Maybe I'm configuring it wrong?

**Comment by ewr** [comment]
You'll want to select Icecast 2. Apparently Icecast 1 doesn't start with a request we recognize. It's a bug that it crashes instead of just discarding the connection, though. 

Unrelated to your issue, but if you're running StreamMachine after installing from NPM, you might want to install from master instead. There's a lot of good new code that hasn't been pushed out as a release to NPM yet. I've mostly been waiting until I get the docs updated before I push a new version, but the code itself is running well.

**Comment by pedropapa** [comment]
I installed it using git clone command from master branch.

Thank you for the help, I'll test it out and post the results here.

**Comment by ewr** [comment]
Perfect. Make sure you're starting up with a config file... In your pasted log output, it looks like you might not be. `./streammachine-cmd --config ./config/standalone.json` would give you the included example config, which has an mp3 stream called `test`.

**Comment by pedropapa** [comment]
Thank you very much for your attention @ewr 

Everything is up and running now! it worked even using forever to make sure it will always be up and running.
```
forever start index.js --config ./config/standalone.json
```


Sorry about my bad english.
