### ISSUE TITLE
Any facility to stream a playlist?

### ISSUE THREAD

**Issue by coeus-abdullahaziz** [StreamMachine/StreamMachine#49]
If this stream machine can play playlists in different ports, please let me know how if not then i am willing to add this functionality in it. Please clear road map of understanding this to me. Thanks
@ewr @sdillingham @bricker  @pteich

**Comment by coeus-abdullahaziz** [comment]
How can i send the playlist to streamingMachine which will play the all tracks and then if finished, play again.

**Comment by ewr** [comment]
Thanks for clarifying... That's not currently something that StreamMachine handles. It is concerned with live sources, not with managing local files as sources. In our world, that playlist would typically be managed on a different system somewhere, with just the one stream being sent on to StreamMachine.

It would certainly be possible if you wanted to write a custom source, but it isn't in the development roadmap at the moment.

**Comment by coeus-abdullahaziz** [comment]
So There is no way to play multiple mp3 file one after another? Because I need it. Like you give a path of single mp3, what if you give a array of files and when one get finish the other file should start stream. please tell me if there is any possibility. Thanks.

@ewr  @sdillingham  @bricker  @pteich

**Comment by ewr** [comment]
That's correct. That isn't a function that StreamMachine supports, and isn't currently in our roadmap.

**Comment by coeus-abdullahaziz** [comment]
So can you give me some clue and direction, how can i do that thing with this streaming machine. Because i need to do it. 
@ewr

**Comment by CoDEmanX** [comment]
I'm interested in this too, and I know some JS and Node. Some directions on how to implement this are highly appreciated. Perhaps I can make a PR at some point.

**Comment by 5punk** [comment]
I've figured it out.
I've updated the documentation to help others who have been frantically looking for help, I've also added documentation to allow playlists, multiple mp3 files and directories :)

https://github.com/StreamMachine/StreamMachine/wiki/Setting-up-a-local-stream-with-VLC-or-LiquidSoap
