### ISSUE TITLE
Tests fail on Node 4.0

### ISSUE THREAD

**Issue by ewr** [StreamMachine/StreamMachine#50]
Two tests fail on Node 4.0:

* One appears to just need an Elasticsearch client update.
* The other appears to be a potentially deeper issue in our use of socket.io.

**Comment by ewr** [comment]
This was fixed via 1109dcb94ac10759393ebd88dd842b9327e5f52f and febdbe06b74215c7c4ca428662019b2f53dc0c93.

**Comment by CoDEmanX** [comment]
So v4.0 is supported? Unfortunately, some socket.io dependencies require 0.12 to build successfully on Windows. I wonder if I could npm install deps using the older node, then switch to 4.x to actually run StreamMachine.

**Comment by ewr** [comment]
The tests pass... I haven't run 4.0 in production yet, so I can't make any promises there.

I haven't ever run node on Windows, so I can't speak to the socket dep issues.
