### ISSUE TITLE
ProxyRoom + Master/Slave connection issues

### ISSUE THREAD

**Issue by cdgraff** [StreamMachine/StreamMachine#72]
The Slave connection go down when Master using ProxyRoom, and the Icecast source go down, master reconnect correctly to Icecast source but Slave don't recover the stream.

Step to reproduce:
1- Setup Master/Slave StreamMachine
2- Connect Master to a Icecast usign Fallback setting (ProxyRoom)
3- Stop Icecast or Disconnect source inside icecast server
4- Start Icecast or Reconnect source again
5- Try to listen inside Slave url.

Logs here: https://gist.github.com/cdgraff/e3420181b6726927d457

Restarting Master process, slave start to work again and listen correctly

**Comment by ewr** [comment]
I want to get a test written before I close this issue, but I believe that commit should fix the lack of reconnection.

One thing to note: When a client connects to an Icecast server (or to StreamMachine as a shoutcast / raw listener), the server will typically burst some audio before settling down to the cadence of the actual stream. When we're connecting to another server via the proxy source, that's going to play a little funny with our concept of the timestamp of the audio coming into the server. This is mostly an issue for HLS, though.

**Comment by ewr** [comment]
Tests are implemented in 71822c4.

**Comment by cdgraff** [comment]
Hi Eric, today I has an episode again... in this case take me much more time to fix, i has need to remove the DUMP feature to be sure that when start all work well.

The difference I found today, was when listen using RAW output the last seconds go in loop.

Here full log output: https://goo.gl/uLmWTx

The issue start on: Jan 10 15:42:55

I'm running latest code from master (cors feature included)

thanks!
