### ISSUE TITLE
ProxySource issue still there 

### ISSUE THREAD

**Issue by cdgraff** [StreamMachine/StreamMachine#74]
Related with https://github.com/StreamMachine/StreamMachine/issues/72

Hi Eric, today I has an episode again... in this case take me much more time to fix, i has need to remove the DUMP feature to be sure that when start all work well.

The difference I found today, was when listen using RAW output the last seconds go in loop.

Here full log output: https://goo.gl/uLmWTx

The issue start on: Jan 10 15:42:55

I'm running latest code from master (cors feature included)

thanks!

**Comment by ewr** [comment]
I'm not sure I see real crash info in there. I see the source losing its connection and attempting reconnects, and I see the message that the process exited, but I don't see any indication of why.

There are a lot of the source disconnect logs between 15:42 and 15:50. Was there a valid reason SM should have lost its connection to the source during that time?

The loop could just be a client-side thing (lots of clients reconnect and get re-buffered the same data when they stop getting new data), or if the source was getting its connection back and losing it again, it could have been getting sent the same original data but giving it a new timestamp.

**Comment by cdgraff** [comment]
In this current setup, the customer use BUTT that is not directly compatible with SM, for this reason publish into Icecast and SM pull from them.

During this time, the Source has internet issues, and reconnect many times into Icecast
This is the icecast logs filtered for source only data
https://gist.github.com/cdgraff/5d09266285d29aa40f50

The loop was in RAW over Chrome
I'll try to get more data when this happen again.

Thanks!
