### ISSUE TITLE
Webrtc audio stream

### ISSUE THREAD

**Issue by timonsk** [StreamMachine/StreamMachine#75]
Hi all!
Can we configure StreamMachine  source input for Webrtc audio stream?
How can we configure source input for multiple files streams etc.?
Thank you!

**Comment by ewr** [comment]
We don't currently support WebRTC, but I'd be interested to hear more about the use case you've got.

Source Mounts support multiple sources, but there isn't currently a source that would play out a playlist of files, or anything like that. You would want to do that outside of StreamMachine and just send in a normal source signal.

**Comment by timonsk** [comment]
Hi all!
The main idea is to create web control which will work with microphone and some mp3 or wav tracks in web page and you can access to it from anywhere and any device. Only you need is a microphone and internet, you will not depend on your system(win, mac, linux).
I found some js solutions like https://github.com/webcast/webcaster, but it no longer supported.
So probably it will be nice to have such fitch's in #StreamMachine.
Thank you alot for your answer.

**Comment by maurodelazeri** [comment]
It works well if you integrate with liquidsoap and then stream machine

**Comment by timonsk** [comment]
Hi @maurodelazeri  do you have any example of  integrate webcaster with liquidsoap?
It will be nice if you'll provide something. 
Thank's a lot!

**Comment by maurodelazeri** [comment]
Check it out @timonsk 

http://freedrool.us/blog/webcaster/

**Comment by timonsk** [comment]
@maurodelazeri  Thank' s a lot!

**Comment by ewr** [comment]
Thanks for jumping in @maurodelazeri!
