### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by maurodelazeri** [StreamMachine/StreamMachine#79]
ssh is supported?

**Comment by ewr** [comment]
Not directly. That hasn't been something we've rolled out in production yet, but my plan is to use HAProxy to do to termination in front of StreamMachine, rather than adding support into this codebase.

**Comment by cdgraff** [comment]
@ewr i do the experience of use HAProxy in front of Icecast before, and is a big funnel, HAProxy don't work well (CPU use is really high) when all the streaming traffic go over there... i think for HLS can works but for Raw audio in my experience was terrible.

I try with my own HAProxy and with Amazon ELB, (based on HAProxy too) and the CPU use was 50% of CPU available into the server, when icecast process just use 10% managing the same traffic.

**Comment by ewr** [comment]
That's fair. There may be scales where other tools are more appropriate for the SSL termination. nginx could do it, as could a variety of other options. I would suspect one of them would provide the appropriate performance, and that still seems like a less complex option than managing termination internally in StreamMachine. Not that I wouldn't take a PR if someone wanted to go down that road...

**Comment by maurodelazeri** [comment]
I'm testing with haproxy and I'm not having trouble, I'm simulating more than 2000 simultaneous connections @ewr @cdgraff

**Comment by ewr** [comment]
Yeah. We've run closer to ~5k on a small HAProxy VM without issues (not SSL termination, though), but that's still small in the grand scheme of things. 

I'm going to close this issue, since I think the original question was answered.

**Comment by maurodelazeri** [comment]
:+1: @ewr
