### ISSUE TITLE
Problem to transcode

### ISSUE THREAD

**Issue by maurodelazeri** [StreamMachine/StreamMachine#80]
**Im with a problem to use ffmeg to reduce the bitrate, my source is liquidsoap (it is like origin coming from icecast), everything works fine, but if I use this configuration bellow to reduce the bitrate I got the following error**

streamer-0 debug: setting framesPerSec to  frames=93.75, source_mount=maurodel, uuid=924e7c41-4efa-4c21-956b-f7eb43ed76ba
streamer-0 debug: first header is  crc=true, mpeg_type=MPEG4, profile=2, sample_freq=96000, channel_config=7, frame_length=6370, buffer_fullness=109, number_of_frames=2, profile_name=AAC LC, channels=8, frames_per_sec=93.75, duration=10.666666666666666, stream_key=aac-96000-2-8, source_mount=maurodel, uuid=924e7c41-4efa-4c21-956b-f7eb43ed76ba
streamer-0 debug: Vitals parsed for source. source_mount=maurodel, uuid=924e7c41-4efa-4c21-956b-f7eb43ed76ba
streamer-0 event: New source is active. new_source=Icecast (172.31.25.212:23153), old_source=undefined, source_mount=maurodel
streamer-0 invalid header...  <Buffer 04 10 1b 3f 2a 32 3e 16 d8> { crc: true,
streamer-0   mpeg_type: 'MPEG4',
streamer-0   profile: 2,
streamer-0   sample_freq: 96000,
streamer-0   channel_config: 7,
streamer-0   frame_length: 6370,
streamer-0   buffer_fullness: 109,
streamer-0   number_of_frames: 2,
streamer-0   profile_name: 'AAC LC',
streamer-0   channels: 8,
streamer-0   frames_per_sec: 93.75,
streamer-0   duration: 10.666666666666666,
streamer-0   stream_key: 'aac-96000-2-8' }
streamer-0 chucking invalid try at header:  <Buffer ff ff fb>
streamer-0 chucking invalid try at header:  <Buffer ff fb c9>
streamer-0 chucking invalid try at header:  <Buffer ff fb 1d>
streamer-0 chucking invalid try at header:  <Buffer ff fa df>
streamer-0 chucking invalid try at header:  <Buffer ff ff ff>

**Conf working**
```json
{
    "streams": {
        "maurodel": {
            "key": "maurodel",
            "source_password": "test",
            "hls": {
                "segment_duration": 10,
                "limit_full_index": false
            },
            "preroll": "",
            "transcoder": "",
            "log_interval": 30000,
            "meta_interval": 32768,
            "max_buffer": 4194304,
            "seconds": 14400,
            "burst": 30,
            "host": null,
            "fallback": null,
            "acceptSourceMeta": false,
            "log_minutes": true,
            "monitored": false,
            "metaTitle": "",
            "metaUrl": "",
            "format": "mp3",
            "preroll_key": "",
            "root_route": false,
            "group": null,
            "bandwidth": 0,
            "codec": null,
            "ffmpeg_args": null,
            "stream_key": null,
            "impression_delay": 5000
        }
    },
    "sources": {
        "maurodel": {
            "source_password": "test",
            "format": "aac",
            "monitored": false,
            "password": false
        }
    }
}
```

**Conf with problem**
```json
{
    "streams": {
        "maurodel": {
            "key": "maurodel",
            "format": "aac",
            "seconds": "360",
            "source_password": "test",
            "bandwidth": "64000",
            "codec": "mp4a.40.2",
            "ffmpeg_args": "-c:a libfdk_aac|-b:a 64k|-f:a adts|-profile:a aac_he",
            "stream_key": "test",
            "hls": {
                "segment_duration": 10,
                "limit_full_index": false
            },
            "preroll": "",
            "transcoder": "",
            "log_interval": 30000,
            "meta_interval": 32768,
            "max_buffer": 4194304,
            "burst": 30,
            "host": null,
            "fallback": null,
            "acceptSourceMeta": false,
            "log_minutes": true,
            "monitored": false,
            "metaTitle": "",
            "metaUrl": "",
            "preroll_key": "",
            "root_route": false,
            "group": null,
            "impression_delay": 5000
        }
    },
    "sources": {
        "maurodel": {
            "source_password": "test",
            "format": "aac",
            "monitored": false,
            "password": false
        }
    }
}
```

**Here is my ffmeg instaled:**

ffmpeg version N-77455-g4707497 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --mandir=/usr/share/man --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libfreetype --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      55. 11.100 / 55. 11.100
  libavcodec     57. 20.100 / 57. 20.100
  libavformat    57. 20.100 / 57. 20.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 21.101 /  6. 21.101
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Comment by ewr** [comment]
My gut says the problem's in the incoming source data, not in the transcoding config. What encoding is supposed to be coming out of liquidsoap?

**Comment by maurodelazeri** [comment]
It is mp3
Should I send some other kind of encode as ACC?

Ps: If I don't do transcoding it works very well mp3

output.icecast(%mp3,
  icy_metadata = "false",
  host = stream_host, port = stream_port,
  password = pass, mount = "#{mount_name}",
  source)

**Comment by ewr** [comment]
Ah. In the transcoding config you're specifying that the stream will be AAC, but it doesn't know to be expecting mp3 source input. 

That's fully supported, though. Just use separate configuration for the stream and the source mount. Assuming you're hardcoding the settings via the config file:

```json
{
  "sources": {
    "maurodel": {
      "format": "mp3",
      "monitored": false,
      "password": "test"
    }
  },
  "streams": {
    "maurodel": {
      "key": "maurodel",
      "format": "aac",
      "seconds": 360,
      "bandwidth": "64000",
      "codec": "mp4a.40.2",
      "ffmpeg_args": "-c:a libfdk_aac|-b:a 64k|-f:a adts|-profile:a aac_he",
      "source": "maurodel"
    }
  }
}
```

**Comment by maurodelazeri** [comment]
Yes, you are right :+1: 

ps: anyway in the configuration that I sent just changing the output format for acc plus also works perfectly

**output.icecast(%aacplus,
  icy_metadata = "false",
  host = stream_host, port = stream_port,
  password = pass, mount = "#{mount_name}",
  source)**

**Comment by ewr** [comment]
Cool. Glad to hear it.

Yeah, If SM sets up the source mount automatically, it assumes the same source format as the stream's output format. Sending AAC data would work fine, but sometimes it's nice to transcode one to the other. For instance, at KPCC in production we take one AAC source in and produce multiple AAC variants for HLS and one MP3 stream for older clients.

**Comment by maurodelazeri** [comment]
I get it,tks
In my case I can use only one format because the client are using my player on mobile or web.

I saw that sometimes when the audio stream is interrupted between the source and the Stream Machine when it is connected, does not running normally to reconnect the source stream.
I can see in the logs that the connection came back and is connected but not back to work

Maybe I should use a fallback?

**Comment by ewr** [comment]
If you get a good example of that, open that as an issue. I haven't seen any issues with a new source not causing data to resume flowing to a client.

**Comment by maurodelazeri** [comment]
Sure, I'll open a new detailed issue with logs
